---
# tasks file for proxmox_management

- name: Proxmox
  ansible.builtin.include_tasks:
    file: proxmox/prep-proxmox.yml
- name: Required user check
  ansible.builtin.include_tasks:
    file: proxmox/user-check.yml
- name: Update VM templates
  ansible.builtin.include_tasks:
    file: proxmox/create-cloudinit.yml
# - name: Last tasks
#   ansible.builtin.include_tasks:
#     file: run-this-last.yml
