---
- name: Set fact for user existence
  ansible.builtin.set_fact:
    user_json: "{{ userlist.stdout | from_json }}"
  ignore_errors: true
  no_log: true

  # register: command_result
  # failed_when: not "'FAILED' in command_result.stderr"

- name: Check if {{ item.username }} exists
  ansible.builtin.set_fact:
    user_exists: "{{ user_json | json_query(user_query) | length > 0 }}"
  vars:
    user_query: "[?userid=='{{ item.username }}@{{ proxmox_management_user_realm }}']"
  register: command_result
  failed_when: not "'FAILED' in command_result.stderr"

- name: Ensure the Proxmox system user exists
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: true
  when: not user_exists
  ignore_errors: true

- name: Create Proxmox user if does not exists
  ansible.builtin.command: pveum useradd {{ item.username }}@{{ proxmox_management_user_realm }} --password {{ item.password }} --email {{ item.email }} --group admin
  when: not user_exists
  ignore_errors: true
