---

- name: Ensure Proxmox is updated
  apt:
    update_cache: true
    upgrade: true

- name: Ensure Proxmox VE is installed
  apt:
    name: proxmox-ve
    state: present

- name: Ensure Proxmox services are running
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - pve-cluster
    - pvedaemon
    - pveproxy

- name: Remove to subscription repos
  apt_repository:
    repo: >
      deb https://enterprise.proxmox.com/debian/pve
      bookworm pve-enterprise
    state: absent

- name: Switch to community repos
  apt_repository:
    repo: >
     deb http://download.proxmox.com/debian/pve
     bookworm pve-no-subscription
    state: present

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install apt packages
  apt:
    name: "{{ packages }}"
    state: latest

- name: pip update pip
  pip:
    name: pip
    state: latest
    extra_args: --break-system-packages

- name: Install dependencies
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: --break-system-packages
  loop:
    - virtualenv
    - proxmoxer
    - passlib
