---
- name: Check if Proxmox user exists
  ansible.builtin.command: pveum user list --output-format=json
  register: userlist
  changed_when: false

- name: Parse userlist and Create Proxmox user if not exists
  ansible.builtin.include_tasks: create-user.yml
  loop: "{{ proxmox_management_user_list }}"
