---
# tasks file for proxmox_management

- name: Proxmox
  ansible.builtin.include_tasks:
    file: proxmox/prep-proxmox.yml
- name: Create Ansible group
  ansible.builtin.include_tasks:
    file: proxmox/create-groups.yml
- name: Required user check
  ansible.builtin.include_tasks:
    file: proxmox/user-check.yml
