---
# Configure Localhost for the subsequent playbooks.
- name: Update Ansible Host with required settings.
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - ~/secrets/creds.yml
  vars:
    ansible_become_pass: "{{ become_password }}"
    apt_packages:
      - unzip
      - python3-pip
      - python3
      - build-essential
      - libguestfs-tools
    pip_packages:
      - pyyaml
      - jinja2
      - httplib2
      - paramiko
      - cryptography
      - ansible-lint
      - passlib
      - bcrypt
      - lxml
      - simplejson
      - pywinrm
      - netaddr
  tasks:
    - name: Install required apt packages
      apt:
        name: "{{ apt_packages }}"
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Install pip dependencies
      pip:
        name: "{{ pip_packages }}"
        state: present
