---
# vm_init  


# TL;DR variables for quick use
global_description: "Created with Ansible on {{ ansible_date_time.date }}"
global_node: 'proxmox'
global_keyboard: 'en-us'

# Overwrite default variables for all VMs
global:
  acpi: 'true'
  # Enable QEMU Agent, remember to install qemu-guest-agent on VMs 
  agent: 'true'
  api_host: "{{ var_api_host }}"
  api_user: "{{ var_api_user }}"
  api_password: "{{ var_api_password }}"
  api_token_id: "{{ var_api_token_id }}"
  api_token_secret: "{{ var_api_token_secret }}"
  args: '-serial unix:/var/run/qemu-server/<vmid>.serial,server,nowait' # args must be ran with Root@pam for proxmox. 
  autostart: 'true'
  balloon: '0'
  bios: ''
  # Boot from disk and network
  boot: 'cnd'
  bootdisk: ''
  clone: 'goldenimage-Ubuntu-22.04-v1'
  cores: '1'
  cpu: 'kvm64'
  cpulimit: ''
  cpuunits: '1000'
  delete: ''
  description: '{{ global_description }}'
  digest: ''
  # Set force to empty value because of a bug
  force: ''
  format: 'unspecified'
  freeze: ''
  full: ''
  hostpci: ''
  # Disable hotplug for 'network', 'disk', 'cpu', 'memory' and 'usb'
  hotplug: '0'
  hugepages: ''
  ide: ''
  keyboard: '{{ global_keyboard }}'
  kvm: 'true'
  localtime: ''
  lock: ''
  machine: ''
  memory: '1024'
  migrate_downtime: ''
  migrate_speed: ''
  name: ''
  net: ''
  newid: ''
  node: '{{ global_node }}'
  numa: ''
  numa_enabled: ''
  onboot: 'true'
  ostype: 'l26'
  parallel: ''
  pool: 'Test'
  protection: ''
  # Set behavior to compatibility because of "force" bug
  proxmox_default_behavior: 'no_defaults'
  reboot: ''
  revert: ''
  sata: ''
  scsi: ''
  # virtio-scsi-pci for better performance
  scsihw: 'virtio-scsi-pci'
  serial: ''
  shares: ''
  skiplock: ''
  smbios: ''
  snapname: ''
  sockets: '1'
  startdate: ''
  startup: ''
  state: 'present'
  storage: ''
  tablet: 'false'
  target: ''
  tdf: ''
  template: 'false'
  # Time out required as the default of 30 seconds is much to short for a full clone. 
  timeout: '500'
  update: ''
  validate_certs: ''
  vcpus: ''
  vga: 'std'
  virtio: ''
  vmid: ''
  watchdog: ''
