---
# - name: Start the VM
#   community.general.proxmox_kvm:
#     api_host: "{{ api_host }}"
#     api_user: "{{ api_user }}"
#     api_token_id: "{{ dev_vault_api_token_id}}"
#     api_token_secret: "{{ dev_vault_api_token_secret }}"
#     vmid: "{{ prometheus_vmid }}"
#     state: current
#   ignore_errors: true
#   register: state

# - name: test SSH connection
#   wait_for:
#     host: "{{ vm_ip }}"
#     port: 22
#     timeout: 10
#   ignore_errors: true
#   register: ssh

- name: If current state of Prometheus VM is not Started
  block:
    - name: Clone the goldenimage-Ubuntu-22.04 template to a new VM
      community.general.proxmox_kvm:
        api_host: "{{ vm_init_api_host }}"
        api_user: "{{ vm_init_api_user }}"
        api_token_id: "{{ vm_init_api_token_id }}"
        api_token_secret: "{{ vm_init_api_token_secret }}"
        node: "{{ vm_init_proxmox_node }}"
        clone: goldenimage-Ubuntu-22.04
        newid: "{{ vm_init_prometheus_vmid }}"
        name: Prometheus-{{ vm_init_env }}
        full: true
        storage: "{{ vm_init_vm_storage }}"
        format: qcow2
        state: present
        citype: nocloud
        timeout: 500

    - name: Set VM hardware and cloud-init configurations
      community.general.proxmox_kvm:
        api_host: "{{ vm_init_api_host }}"
        api_user: "{{ vm_init_api_user }}"
        api_token_id: "{{ vm_init_api_token_id }}"
        api_token_secret: "{{ vm_init_api_token_secret }}"
        vmid: "{{ vm_init_prometheus_vmid }}"
        node: "{{ vm_init_proxmox_node }}"
        memory: 4096
        cores: 2
        sockets: 1
        onboot: true
        ipconfig:
          ipconfig0: ip={{ vm_init_vm_ip }}/24,gw={{ vm_init_gateway_ip }}
        searchdomains: "{{ vm_init_searchdomain }}"
        nameservers: "{{ vm_init_vm_dns }}"
        update: true
        ciuser: ansibleadmin
        cipassword: "{{ vm_init_ci_password }}"
        sshkeys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        timeout: 300

    # - name: Update existing disk size
    #   community.general.proxmox_disk:
    #     api_host: "{{ vm_init_api_host }}"
    #     api_user: "{{ vm_init_api_user }}"
    #     api_token_id: "{{ vm_init_api_token_id }}"
    #     api_token_secret: "{{ vm_init_api_token_secret }}"
    #     vmid: "{{ vm_init_prometheus_vmid }}"
    #     disk: scsi0
    #     size: 10G
    #     state: present

    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ vm_init_api_host }}"
        api_user: "{{ vm_init_api_user }}"
        api_token_id: "{{ vm_init_api_token_id }}"
        api_token_secret: "{{ vm_init_api_token_secret }}"
        vmid: "{{ vm_init_prometheus_vmid }}"
        state: started
      register: result
      notify: pause 300

    # - name: Wait for SSH to come up
    #   ansible.builtin.wait_for:
    #     host: "{{ vm_init_vm_ip }}"
    #     port: 22
    #     state: started
    #     delay: 0
    #     timeout: 60
    #   # ignore_errors: true
    #   register: vm
    #   until: vm is not failed
    #   retries: 10
