- name: clone cloud-init from template
    community.general.proxmox_kvm:
      api_host: "{{ api_host }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ vault_api_token_id}}"
      api_token_secret: "{{ vault_api_token_secret }}"
      proxmox_node: "proxmox"
      proxmox_default_behavior: "compatibility"
      clone: CloudInitBase
      newid: "{{ item.value.vmid }}"
      full: "{{ item.value.full }}"
      #name: "{{ item.key }}"
      cores: '{{ item.value.cores | default(defaults.cores) }}'
      memory: '{{ item.value.memory_size | default(defaults.memory_size) }}'
      balloon: '{{ item.value.balloon | default(defaults.balloon) }}'
      vga: 'serial0'
      ostype: '{{ item.value.ostype | default(defaults.ostype) }}'
      cpu: '{{ item.value.cpu | default(defaults.cpu) }}'
      vcpus: '{{ item.value.vcpus | default(defaults.vcpus) }}'
      bootdisk: "scsi0"
      net: '{{ item.value.net | default(defaults.net) }}'
      ipconfig: '{{ item.value.ipconfig | default(defaults.ipconfig) }}'
      format: 'unspecified'
      virtio: '{{ item.value.virtio | default(defaults.virtio) }}'
      scsihw: '{{ item.value.scsihw | default(defaults.scsihw) }}'
      timeout: 600
    with_dict: "{{ vm_list }}"