---
# defaults file for proxmox_management

# Prep-Proxmox:
proxmox_management_packages:
  - python3-pip
  - python3
  - build-essential

proxmox_management_user_realm: pam
proxmox_management_user_list: "{{ vault_proxmox_userlist}}"
