---
vm_init_list:
  - name: prometheus-dev
    newid: 1000
    virtio: {"virtio0":"LVM-Prime:20"}
    bootdisk: 'virtio0'
    cores: 2
    cpus: 2
    memory: 4096
    pool: 'Dev'
    # ipconfig: {"ipconfig0":"ip=192.168.1.112/24,gw=192.168.1.1/24"}
    nic:
      interface: 'net0'
      bridge: 'vmbr0'
      mac: 'BC:24:11:46:1A:80'
      firewall: false
  - name: portainer-dev
    newid: 1100
    # net: {"net0":"virtio=BC:24:11:46:1A:88,bridge=vmbr0"}
    virtio: {"virtio0":"LVM-Prime:20"}
    bootdisk: 'virtio0'
    cores: 2
    cpus: 2
    memory: 4096
    pool: 'Dev'
    # ipconfig: {"ipconfig0":"ip=192.168.1.34/24,gw=192.168.1.1/24"}
    nic:
      interface: 'net0'
      bridge: 'vmbr0'
      mac: 'BC:24:11:46:1A:88'
      firewall: false
  - name: vault-dev
    newid: 1200
    # net: {"net0":"virtio=BC:24:11:B1:7F:46,bridge=vmbr0"}
    virtio: {"virtio0":"LVM-Prime:20"}
    bootdisk: 'virtio0'
    cores: 2
    cpus: 2
    memory: 4096
    pool: 'Dev'
    # ipconfig: {"ipconfig0":"ip=192.168.1.27/24,gw=192.168.1.1/24"}
    nic:
      interface: 'net0'
      bridge: 'vmbr0'
      mac: 'BC:24:11:46:1A:46'
      firewall: false
  - name: prometheus-prd
    newid: 3000
    virtio: {"virtio0":"LVM-Prime:20"}
    bootdisk: 'virtio0'
    cores: 2
    cpus: 2
    memory: 4096
    pool: 'Prod'
    # ipconfig: {"ipconfig0":"ip=192.168.1.112/24,gw=192.168.1.1/24"}
    nic:
      interface: 'net0'
      bridge: 'vmbr0'
      mac: 'BC:24:11:46:1B:80'
      firewall: false
  - name: portainer-prd
    newid: 3100
    # net: {"net0":"virtio=BC:24:11:46:1A:88,bridge=vmbr0"}
    virtio: {"virtio0":"LVM-Prime:20"}
    bootdisk: 'virtio0'
    cores: 2
    cpus: 2
    memory: 4096
    pool: 'Prod'
    # ipconfig: {"ipconfig0":"ip=192.168.1.34/24,gw=192.168.1.1/24"}
    nic:
      interface: 'net0'
      bridge: 'vmbr0'
      mac: 'BC:24:11:46:1B:88'
      firewall: false
  - name: vault-prd
    newid: 3200
    # net: {"net0":"virtio=BC:24:11:B1:7F:46,bridge=vmbr0"}
    virtio: {"virtio0":"LVM-Prime:20"}
    bootdisk: 'virtio0'
    cores: 2
    cpus: 2
    memory: 4096
    pool: 'Prod'
    # ipconfig: {"ipconfig0":"ip=192.168.1.27/24,gw=192.168.1.1/24"}
    nic:
      interface: 'net0'
      bridge: 'vmbr0'
      mac: 'BC:24:11:46:1B:46'
      firewall: false
  - name: vault-raft-prd-01
    newid: 3201
    # net: {"net0":"virtio=BC:24:11:B1:7F:46,bridge=vmbr0"}
    virtio: {"virtio0":"LVM-Prime:20"}
    bootdisk: 'virtio0'
    cores: 2
    cpus: 2
    memory: 4096
    pool: 'Prod'
    # ipconfig: {"ipconfig0":"ip=192.168.1.27/24,gw=192.168.1.1/24"}
    nic:
      interface: 'net0'
      bridge: 'vmbr0'
      mac: 'BC:24:11:46:1B:47'
      firewall: false
  - name: vault-raft-prd-02
    newid: 3202
    # net: {"net0":"virtio=BC:24:11:B1:7F:46,bridge=vmbr0"}
    virtio: {"virtio0":"LVM-Prime:20"}
    bootdisk: 'virtio0'
    cores: 2
    cpus: 2
    memory: 4096
    pool: 'Prod'
    # ipconfig: {"ipconfig0":"ip=192.168.1.27/24,gw=192.168.1.1/24"}
    nic:
      interface: 'net0'
      bridge: 'vmbr0'
      mac: 'BC:24:11:46:1B:48'
      firewall: false
