---
# defaults file for proxmox_management

# Prep-Proxmox:
packages:
    - python3-pip
    - python3
    - build-essential

# VM-Init

force_download: true
public_keys: "{{ ssh_pubkey }}"
api_host: "proxmox"
api_user: "ansibleadmin@pam"
var_api_token_id: "{{ vault_api_token_id }}"
var_api_token_secret: "{{ vault_api_token_secret }}"
node_target: "proxmox"
img_download_version: "jammy"
img_target_name: "jammy-server-cloudimg-amd64"
img_source_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
img_target_path: "~/"
img_download_target_path: "/home/bsmits/downloads"
iso_target_path: "{{img_target_path}}{{img_target_name}}.qcow2"
storage_target: "local-lvm"
# vm_defs:
#   - id: 2001
#     name: "cloudimage-base"
#     nets:
#       - id: 0
#         bridge: "vmbr0"

user_realm: "pam"
user_list:
    - username: bsmits
      email: barrett.smits@gmail.com
      password: "{{ vault_bsmits_password }}"
    - username: dkasten
      email: kastendl@gmail.com
      password: "{{ vault_dkasten_password }}"
    - username: ansibleadmin
      email: barrett.smits+ansibleadmin@gmail.com
      password: "{{ vault_ansible_password }}"
    - username: test
      email: barrett.smits+ansibletest@gmail.com
      password: "{{ vault_test_password }}"
