---
- name: Initiate Packer golden_image for proxmox VMs 
  hosts: localhost
  gather_facts: false
  become: true
  become_user: bsmits
  vars_files:
    - ~/secrets/creds.yml
  vars:
    use_force: false
    version_num: 22.04
    path: "~/wsl_src/packer_golden_image"
    ansible_become_pass: "{{ become_password }}"
  environment:
    # these are for Dev Vault server. add to vault for production 
    VAULT_TOKEN: ''
    VAULT_ADDR: 'http://127.0.0.1:8200'
  tasks:
    - name: Run Packer to build target image (this will take a while)
      no_log: false
      shell: |
        cd {{ path }}
        packer build -color=false {{ '-force' if use_force | bool else '' }} -var-file {{ version_num }}.pkrvars.hcl .
      register: packer_result
      failed_when: "'successful build' not in packer_result.stdout"
      changed_when: true

    - name: Display Packer command output
      debug:
        var: packer_result.stdout